# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    vehicle.car:
      class: AppBundle\Transport\Car

    vehicle.bike:
      class: AppBundle\Transport\Bike

    vehicle.manager:
      class: AppBundle\Transport\VehicleManager
      arguments: ['@vehicle.bike']

