# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  manager.default:
    class: AppBundle\Manager\DefaultManager
    arguments: ['@doctrine.orm.entity_manager']
