# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  subscriber.bind_coucou:
    class: AppBundle\EventSubscriber\BindCoucouSubscriber
    tags:
        - { name: kernel.event_subscriber }