# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    music.hurricane_season:
      class: AppBundle\Music\HurricaneSeason
      tags: ['app.music']

    music.new_fang:
          class: AppBundle\Music\NewFang
          tags: ['app.music']

    music.old_friend:
          class: AppBundle\Music\OldFriend
          tags: ['app.music']

    music.collection:
      class: AppBundle\Music\MusicCollection
